### PR TITLE
Typo "**App fps: **"→"**App fps:**"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.debugsettings.enableframeratecounter?view=winui-3.0-preview

### CODE REVIEW

**Comment by PRMerger18** [comment]
@hyoshioka0128 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
The formatting fix looks good; merging. Thanks @hyoshioka0128

**Comment by ktoliver** [comment]
@Karl-Bridge-Microsoft In the two tables, are the asterisks that are visible meant to be literal asterisk values or is it an attempt to make the enclosed text italic? If the latter, asterisks won't work because the table is created by using HTML. To get italic font there, you'd need to use `<i></i>`. (Or change the table to Markdown.) I'd fix it but not sure about the intention. Thanks!

**Comment by Karl-Bridge-Microsoft** [comment]
@ktoliver - thanks for pointing this out. I've updated the topic with revised formatting.

**Pull request merged**
