### PR TITLE
Add doc for MaximumRowsOrColumns property

### PR DESCRIPTION
**Pull request by marcelwgn**
Currently there is no documentation for the MaximumRowsOrColumns property. This PR fixes this.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@chingucoding : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @Karl-Bridge-Microsoft - Would you review the proposed update to your article? 

If the PR is approved, the PR review team can remove the locale from the microsoft.com link before merging.

Thanks.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger18** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
