### PR TITLE
Update documentation for TreeView SelectedItem

### PR DESCRIPTION
**Pull request by marcelwgn**
This adds the new TreeView SelectedItemProperty, and adjusts the SelectedItem property text.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@chingucoding : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @Karl-Bridge-Microsoft - Does the new file need to be added to a TOC? Thanks.

**Comment by marcelwgn** [comment]
@ranjeshj @MikeHillberg FYI since the API is only available in prereleases right now.

**Comment by Karl-Bridge-Microsoft** [comment]
hi @ktoliver, no new file. Just an update to two files for a feature released in last milestone. Full descriptions were overlooked for some reason.

**Comment by Karl-Bridge-Microsoft** [comment]
@ktoliver - sorry, missed the new topic! Hold off on the merge! Thanks

**Review by Karl-Bridge-Microsoft — CHANGES_REQUESTED** [review]
Please remove the new file from this PR. This property is not in the official 2.4 release.

**Comment by marcelwgn** [comment]
@Karl-Bridge-Microsoft When should the documentation be adjusted for the newly added SelectedItemProperty, which is available in a prerelease right now?

**Comment by Karl-Bridge-Microsoft** [comment]
@chingucoding - When we have pre-release docs available for the pre-release APIs. Sorry, I should've caught that you were trying to add API topics.

**Comment by PRMerger15** [comment]
@chingucoding : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by marcelwgn** [comment]
All right. I've removed the file. I also noticed that the SelectedItems page missed informations too, so I've updated that file too.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
