### PR TITLE
Remove Tip that references Sound documentation

### PR DESCRIPTION
**Pull request by sohchatt**
there appears to be an incorrect Tip that got for whatever reason. This control has nothing to do with Sound.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@sohchatt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@GrantMeStrength - Could you review the proposed changes and indicate whether the PR can be merged? Thanks.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
