### PR TITLE
TabView: Add link to guidance doc

### PR DESCRIPTION
**Pull request by stmoy**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@stmoy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @stmoy @Karl-Bridge-Microsoft - This link doesn't work or isn't testable in GitHub preview. Can you confirm that it will work in the context of having the gallery app installed? Will it show up as a broken link for users who don't have the gallery app installed? Thanks.

image

**Comment by stmoy** [comment]
Hi @ktoliver - thank you for testing! I copy-pasted this chunk of code from the NavigationView page: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview  It works there, so I think it should work here? 

It's a special type of link because it launches an app. If you copy-paste `xamlcontrolsgallery:/item/TabView` into the Run dialog (Win+R) on a machine with the Gallery installed, it will open the Gallery to that page.

**Comment by ktoliver** [comment]
@stmoy Cool, thanks! I'll merge the PR.

**Pull request merged**
