### PR TITLE
Add reference to guidelines doc

### PR DESCRIPTION
**Pull request by MikeHillberg**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@MikeHillberg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stmoy** [comment]
Thank you for this contribution @MikeHillberg! To make it look consistent with pages like WUX NavigationView, I opened a parallel PR (#23) which has the [!Tip] markup to make the green box.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger9** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
